CREATE VIEW WIDOK1 AS SELECT LAST_NAME || ' ' || SALARY AS WYNAGRODZENIE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 AND SALARY BETWEEN 2000 AND 7000 ORDER BY LAST_NAME;

CREATE VIEW WIDOK2 AS SELECT &HIRE_DATE, &LAST_NAME FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL AND EXTRACT(YEAR FROM HIRE_DATE) = 2005;

CREATE VIEW WIDOK3 AS SELECT FIRST_NAME||' '||LAST_NAME AS EMPLOYEE, SALARY, PHONE_NUMBER FROM EMPLOYEES WHERE LAST_NAME LIKE '__e%' AND FIRST_NAME LIKE '%' || '&WARTOSC' || '%' ORDER BY 1 DESC, 2 ASC;

CREATE VIEW WIDOK4 AS SELECT FIRST_NAME, LAST_NAME, ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE)) AS PRZEPRACOWANE_MIESIACE, (CASE WHEN ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE))<150 THEN 0.1*SALARY WHEN ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE))>200 THEN 0.3*SALARY ELSE 0.2*SALARY END) AS DODATEK FROM EMPLOYEES ORDER BY 3 DESC;

CREATE VIEW WIDOK5 AS SELECT DEPARTMENT_ID, SUMA, SREDNIA FROM(SELECT ROUND(SUM(SALARY)) AS SUMA, ROUND(AVG(SALARY)) AS SREDNIA, ROUND(MIN(SALARY)) AS MIN, DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID) WHERE MIN>5000;

CREATE VIEW WIDOK6 AS SELECT EMPLOYEES.LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.JOB_ID FROM EMPLOYEES INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID WHERE LOCATIONS.CITY='Toronto';

CREATE VIEW WIDOK7 AS SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Jennifer');

CREATE VIEW WIDOK8 AS SELECT DEPARTMENTS.* FROM DEPARTMENTS WHERE DEPARTMENTS.DEPARTMENT_ID NOT IN (SELECT EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL);

CREATE TABLE MOLUSZYS.JOB_GRADES AS SELECT * FROM HR.JOB_GRADES; 

CREATE VIEW WIDOK10 AS SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, EMPLOYEES.JOB_ID, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.SALARY, JOB_GRADES.GRADE FROM EMPLOYEES JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID JOIN JOB_GRADES ON EMPLOYEES.SALARY BETWEEN  JOB_GRADES.MIN_SALARY AND JOB_GRADES.MAX_SALARY;

CREATE VIEW WIDOK11 AS SELECT LAST_NAME, FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES) ORDER BY SALARY DESC;

CREATE VIEW WIDOK12 AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%u%');